# Generated by Django 4.2.3 on 2023-07-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
