# Generated by Django 4.2.3 on 2023-08-03 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0003_alter_ad_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='is_delete',
            new_name='is_deleted',
        ),
    ]
