# Generated by Django 4.2.3 on 2023-08-04 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0005_mymodel_ad_deleted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
